# This is used by the action https://github.com/dorny/paths-filter

go: &go
  - 'go.mod'
  - 'go.sum'
  - '.golangci.yml'
  - 'pkg/**'
  - 'cmd/**'
  - 'internal/**'
  - 'contrib/**'
  - '.github/**'
  - 'mise.toml'
  - '.tool-versions'

docs: &docs
  - 'mkdocs.yml'
  - 'docs/**'
  - 'contrib/**'
  - '**/*.md'
  - 'LICENSE'
  - '.github/**'
  - 'mise.toml'
  - '.tool-versions'

any:
  - *go
  - *docs
