package pam

/*
#include <security/pam_appl.h>
*/
import "C"

const (
	_PAM_SUCCESS               = C.PAM_SUCCESS
	_PAM_OPEN_ERR              = C.PAM_OPEN_ERR
	_PAM_SYMBOL_ERR            = C.PAM_SYMBOL_ERR
	_PAM_SERVICE_ERR           = C.PAM_SERVICE_ERR
	_PAM_SYSTEM_ERR            = C.PAM_SYSTEM_ERR
	_PAM_BUF_ERR               = C.PAM_BUF_ERR
	_PAM_PERM_DENIED           = C.PAM_PERM_DENIED
	_PAM_AUTH_ERR              = C.PAM_AUTH_ERR
	_PAM_CRED_INSUFFICIENT     = C.PAM_CRED_INSUFFICIENT
	_PAM_AUTHINFO_UNAVAIL      = C.PAM_AUTHINFO_UNAVAIL
	_PAM_USER_UNKNOWN          = C.PAM_USER_UNKNOWN
	_PAM_MAXTRIES              = C.PAM_MAXTRIES
	_PAM_NEW_AUTHTOK_REQD      = C.PAM_NEW_AUTHTOK_REQD
	_PAM_ACCT_EXPIRED          = C.PAM_ACCT_EXPIRED
	_PAM_SESSION_ERR           = C.PAM_SESSION_ERR
	_PAM_CRED_UNAVAIL          = C.PAM_CRED_UNAVAIL
	_PAM_CRED_EXPIRED          = C.PAM_CRED_EXPIRED
	_PAM_CRED_ERR              = C.PAM_CRED_ERR
	_PAM_NO_MODULE_DATA        = C.PAM_NO_MODULE_DATA
	_PAM_CONV_ERR              = C.PAM_CONV_ERR
	_PAM_AUTHTOK_ERR           = C.PAM_AUTHTOK_ERR
	_PAM_AUTHTOK_RECOVERY_ERR  = C.PAM_AUTHTOK_RECOVERY_ERR
	_PAM_AUTHTOK_LOCK_BUSY     = C.PAM_AUTHTOK_LOCK_BUSY
	_PAM_AUTHTOK_DISABLE_AGING = C.PAM_AUTHTOK_DISABLE_AGING
	_PAM_TRY_AGAIN             = C.PAM_TRY_AGAIN
	_PAM_IGNORE                = C.PAM_IGNORE
	_PAM_ABORT                 = C.PAM_ABORT
	_PAM_AUTHTOK_EXPIRED       = C.PAM_AUTHTOK_EXPIRED
	_PAM_MODULE_UNKNOWN        = C.PAM_MODULE_UNKNOWN
	_PAM_BAD_ITEM              = C.PAM_BAD_ITEM
	_PAM_CONV_AGAIN            = C.PAM_CONV_AGAIN
	_PAM_INCOMPLETE            = C.PAM_INCOMPLETE
)

const (
	_PAM_SILENT                 = C.PAM_SILENT
	_PAM_DISALLOW_NULL_AUTHTOK  = C.PAM_DISALLOW_NULL_AUTHTOK
	_PAM_ESTABLISH_CRED         = C.PAM_ESTABLISH_CRED
	_PAM_DELETE_CRED            = C.PAM_ESTABLISH_CRED
	_PAM_REINITIALIZE_CRED      = C.PAM_REINITIALIZE_CRED
	_PAM_REFRESH_CRED           = C.PAM_REFRESH_CRED
	_PAM_CHANGE_EXPIRED_AUTHTOK = C.PAM_CHANGE_EXPIRED_AUTHTOK
)

const (
	_PAM_SERVICE      = C.PAM_SERVICE
	_PAM_USER         = C.PAM_USER
	_PAM_TTY          = C.PAM_TTY
	_PAM_RHOST        = C.PAM_RHOST
	_PAM_CONV         = C.PAM_CONV
	_PAM_AUTHTOK      = C.PAM_AUTHTOK
	_PAM_OLDAUTHTOK   = C.PAM_OLDAUTHTOK
	_PAM_RUSER        = C.PAM_RUSER
	_PAM_USER_PROMPT  = C.PAM_USER_PROMPT
	_PAM_FAIL_DELAY   = C.PAM_FAIL_DELAY
	_PAM_XDISPLAY     = C.PAM_XDISPLAY
	_PAM_XAUTHDATA    = C.PAM_XAUTHDATA
	_PAM_AUTHTOK_TYPE = C.PAM_AUTHTOK_TYPE
)
