run:
  timeout: 20m

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - misspell
  disable:
    - ineffassign

linters-settings:
  misspell:
    locale: US
    ignore-words:
      - engity
      - bifröst
      - bifroest

issues:
  exclude-dirs:
    - internal/fmtsort
    - internal/text
  exclude:
    - S1002
    - S1005
    - S1016
    - S1031
    - SA1012
    - SA1019
