run:
  timeout: 20m
  build-tags:
    - without-pam
    - without-yescrypt

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - misspell
  disable:
    - ineffassign

linters-settings:
  misspell:
    locale: US
    ignore-words:
      - engity
      - bifröst
      - bifroest

issues:
  exclude-dirs:
    - internal/fmtsort
    - internal/text
  exclude:
    - S1002
    - S1016
    - SA1012
    - S1031
    - SA1019
