version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - misspell
  disable:
    - ineffassign
  settings:
    misspell:
      locale: US
      ignore-rules:
        - engity
        - bifröst
        - bifroest
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: S1002
      - path: (.+)\.go$
        text: S1005
      - path: (.+)\.go$
        text: S1016
      - path: (.+)\.go$
        text: S1031
      - path: (.+)\.go$
        text: SA1012
      - path: (.+)\.go$
        text: SA1019
    paths:
      - internal/fmtsort
      - internal/text
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
