version: 2

project_name: "Engity's Bifröst"
dist: var/dist
report_sizes: true

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: generic
    main: ./cmd/bifroest
    binary: bifroest
    goos:
      - linux
      - windows
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.edition=generic -X main.version={{.Version}} -X main.revision={{.Commit}} -X main.buildAt={{.Date}} -X main.vendor={{envOrDefault `BIFROEST_VENDOR` `unknown`}}"

  - id: extended
    main: ./cmd/bifroest
    binary: bifroest
    goos:
      - linux
    env:
      - CGO_ENABLED=1
    goarch:
      - amd64
    ldflags:
      - "-s -w -X main.edition=extended -X main.version={{.Version}} -X main.revision={{.Commit}} -X main.buildAt={{.Date}} -X main.vendor={{envOrDefault `BIFROEST_VENDOR` `unknown`}}"

archives:
  - id: generic
    format: tgz
    builds:
      - generic
    name_template: "bifroest-{{ .Os }}-{{ .Arch }}-generic"
    files:
      - LICENSE
      - README.md
      - doc/*
    builds_info:
      group: root
      owner: root

  - id: extended
    format: tgz
    builds:
      - extended
    name_template: "bifroest-{{ .Os }}-{{ .Arch }}-extended"
    files:
      - LICENSE
      - README.md
      - doc/*
    builds_info:
      group: root
      owner: root

##TODO! We should consider to activate this in the future.
##For now it produces too many files (including the checksums) to be very helpful.
#sboms:
#  - id: generic
#    artifacts: archive

checksum:
  split: true

release:
  github:
    owner: engity-com
    name: bifroest
  draft: true
  replace_existing_artifacts: true

changelog:
  use: github
  sort: asc
