ssh:
  addresses: [ ":2022" ]
  idleTimeout: 5m
  maxTimeout: 0
  maxAuthTries: 6
  keys:
    hostKeys: [ var/ssh-key ]
    rememberMeNotification: |

      If you return until {{.Session.Info.ValidUntil | format `dateTimeT`}} with the same public key ({{.Key | fingerprint}}), you can seamlessly login again.


session:
  type: fs
  storage: /var/lib/engity/bifroest/sessions
  fileMode: 666
flows:
  - name: sso
    requirement:
      includedRequestingName: ^sso$
    authorization:
      type: oidcDeviceAuth
      issuer: https://login.microsoftonline.com/my-great-tenant-uuid/v2.0
      clientId: my-great-client-uuid
      clientSecret: very-secret-secret
      scopes:
        - openid
        - email
        - profile
    session:
      idleTimeout: 30m
      maxTimeout: 0
      maxConnections: 10
    environment:
      type: local
      name: "{{.Authorization.IdToken.Claims.email}}"
      displayName: "{{.Authorization.IdToken.Claims.name}}"
      shell: "/bin/bash"
      groups:
        - name: azuread
      createIfAbsent: true
      updateIfDifferent: true
      loginAllowed: |
        {{ and
          (.Authorization.IdToken.Claims.groups | has "my-great-group-uuid")
          (.Authorization.IdToken.Claims.tid    | eq  "my-great-tenant-uuid")
        }}

  - name: local
    authorization:
      type: local
      # Will bypass PAM and check the passwords directly against /etc/shadow
      pamService: ""
      password:
        allowed: true
        interactiveAllowed: true
    session:
      idleTimeout: 30m
      maxTimeout: 0
      maxConnections: 10
    environment:
      type: local
      name: "{{.Authorization.Name}}"
      loginAllowed: |
        {{ or
          (.Authorization.Group.Name | eq "ssh" )
          (.Authorization.Groups     | firstMatching `{{.Name | eq "ssh"}}`)
        }}
