oidc:
  issuer: https://login.microsoftonline.com/my-great-tenant-uuid/v2.0
  clientId: my-great-client-uuid
  clientSecret: very-secret-secret
  scopes:
    - openid
    - email
    - profile
user:
  shell: /bin/bash
  loginAllowed: |
    {{ and
      (.Oidc.IdToken.Claims.groups | has "my-great-group-uuid")
      (.Oidc.IdToken.Claims.tid    | eq "my-great-tenant-uuid")
    }}