apiVersion: v1
kind: Config
current-context: context1

clusters:
  - name: cluster1
    cluster:
      server: http://127.0.0.1:8080
  - name: cluster2
    cluster:
      server: http://127.0.0.2:8080

users:
  - name: user1
  - name: user2

contexts:
  - name: context1
    context:
      cluster: cluster1
      user: user1

  - name: context2
    context:
      cluster: cluster2
      user: user2

